---

- name: Shell
  hosts: bastion
  become: yes
  tasks:
  - name: ss
    shell:
      cme: ssh-copy-id student@192.168.122.10
    
- hosts: baswor
  become: yes
  tasks:
  - name: yum bind
    yum:
      name: bind
      state: present
   
- hosts: bastion
  become: yes
  tasks:
  - name: replace named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      replace: 'listen-on port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on-v6 port 53 { ::1; };'
      replace: 'listen-on-v6 port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      replace: 'allow-query { any; };'
      
  - name: zones
    blockinfile:
      path: /etc/named.rfc1912.zones
      block: |
        zone "dong.com" IN { 
               type master;  
               file "dong.com.zone"; 
               allow-update { none; }; 
        };
      
  - name: create file
    file:
      path: /var/named/dong.com.zone
      state: touch
      
  
  - name: dns
    blockinfile:
      path: /var/named/dong.com.zone
      block: |
        $TTL 3H
        @       IN SOA  ns.dong.com. root.dong.com. (
                                                0       ; serial
                                                1D      ; refresh
                                                1H      ; retry
                                                1W      ; expire
                                                3H )    ; minimum
                IN      NS      ns.dong.com.
        ns      IN      A       192.168.122.10
        okd     IN      A       192.168.122.100

 
  - name: start named
    service:
      name: named
      state: started
      
  - name: enable named
    service:
      name: named
      state: enabled
      
  - name: firewall tcp
    firewalld:
      port: 53/tcp
      permanent: true
      state: enabled
    
  - name: firesall udp
    firewalld:
      port: 53/udp
      permanent: true
      state: enabled
    
  - name: ifcfg p
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: 'DNS=192.168.122.10'
      
  - name: service start net man
    service:
      name: NetworkManager
      state: restarted 
      

- hosts: worker
  become: yes
  tasks:
  - name: replace named.conf
    blockinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      block: |
        NM_CONTROLLED=yes 
        PEERDNS=yes
        DNS1=192.168.122.10
        
  - name: service start net man
    service:
      name: NetworkManager
      state: restart 
   
  - name: ifcfg p
    lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver 192.168.122.10'

    
- hosts: baswor
  become: yes
  tasks:
  - name: add net.ipv4
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'
      
- hosts: bastion
  become: yes
  tasks:
  - name: install openshift
    yum:
      name: centos-release-openshift-origin311.noarch
      state: installed
      
  - name: install ansible
    yum:
      name: openshift-ansible ansible
      state: present
      
  - name: create file
    file:
      path: /usr/share/ansible/openshift-ansible/inventory/hosts.localhost
      state: touch
  
  - name: add inventory
    blockinfile:
      path: /usr/share/ansible/openshift-ansible/inventory/host.localhost
      block: |
        [OSEv3:children]
        masters
        nodes
        etcd
        
        [OSEv3:vars]
        os_firewall_use_firewalld=true
        openshift_pkg_version=-3.11.*
        openshift_deployment_type=origin
        openshift_portal_net=172.30.0.0/16
        openshift_disable_check=disk_availability,memory_availability,docker_image_availability
        
        openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true','node-role.kubernetes.io/compute=true']}]
        
        openshift_master_default_subdomain=okd.dong.com
        openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login':'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

        debug_level=6
        
        ansible_ssh_user=root
        
        ansible_become=true

        openshift_cockpit_deployer_image='docker.io/timbordemann/cockpit-kubernetes:latest'

        [masters]
        okd.dong.com openshift_schedulable=true
        [etcd]
        okd.dong.com
        [nodes]
        okd.dong.com openshift_node_group_name='node-config-all-in-one'
        
        
 
    
    
  
