---
- hosts: controller
  become: yes
  tasks:
  - name: replace named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      replace: 'listen-on port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on-v6 port 53 { ::1; };'
      replace: 'listen-on-v6 port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      replace: 'allow-query { any; };'
      
  - name: zones
    lineinfile:
      path: /etc/named.rfc1912.zones
      line: "{{ item.line }}"
    with_items:
      - { item.line: 'zone "dong.com" IN {'  }
      - { item.line: '        type master;'  }
      - { item.line: '        file "dong.com.zone";' }
      - { item.line: '        file "allow-update { none; };' }
      - { item.line: '};' }
      

      
    
