---
- hosts: controller
  become: yes
  tasks:
  - name: replace named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      replace: 'listen-on port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on-v6 port 53 { ::1; };'
      replace: 'listen-on-v6 port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      replace: 'allow-query { any; };'
      
  - name: zones
    blockinfile:
      path: /etc/named.rfc1912.zones
      block: |
        zone "dong.com" IN { 
               type master;  
               file "dong.com.zone"; 
               allow-update { none; }; 
        };
      
  - name: create file
    file:
      path: /var/named/dong.com.zone
      state: file
  
  - name: dns
    blockinfile:
      path: /var/named/dong.com.zone
      block: |
        $TTL 3H
        @       IN SOA  ns.dong.com. root.dong.com. (
                                                0       ; serial
                                                1D      ; refresh
                                                1H      ; retry
                                                1W      ; expire
                                                3H )    ; minimum
                IN      NS      ns.dong.com.
        ns      IN      A       192.168.122.10
        okd     IN      A       192.168.122.100


