---
- hosts: controller
  become: yes
  tasks:
  - name: yum bind
    yum:
      name: bind
      state: installed 
      
  - name: replace named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      replace: 'listen-on port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'listen-on-v6 port 53 { ::1; };'
      replace: 'listen-on-v6 port 53 { any; };'
      
  - name: named.conf
    replace:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      replace: 'allow-query { any; };'
      
  - name: zones
    blockinfile:
      path: /etc/named.rfc1912.zones
      block: |
        zone "dong.com" IN { 
               type master;  
               file "dong.com.zone"; 
               allow-update { none; }; 
        };
      
  - name: create file
    file:
      path: /var/named/dong.com.zone
      state: touch
      
  
  - name: dns
    blockinfile:
      path: /var/named/dong.com.zone
      block: |
        $TTL 3H
        @       IN SOA  ns.dong.com. root.dong.com. (
                                                0       ; serial
                                                1D      ; refresh
                                                1H      ; retry
                                                1W      ; expire
                                                3H )    ; minimum
                IN      NS      ns.dong.com.
        ns      IN      A       192.168.122.10
        okd     IN      A       192.168.122.100

 
  - name: start named
    service:
      name: named
      state: started
      
  - name: enable named
    service:
      name: named
      state: enabled
      
  - name: firewall tcp
    firewalld:
      port: 53/tcp
      permanent: true
      state: enabled
    
  - name: firesall udp
    firewalld:
      port: 53/udp
      permanent: true
      state: enabled
    
  - name: ifcfg p
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: 'DNS=192.168.122.10'
      
  - name: service start net man
    service:
      name: NetworkManager
      state: restart 
      
      
    
  
